/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChatComponent {
        /**
          * The Chat identifier
         */
        "chatUid"?: string;
        /**
          * The greetings
         */
        "greetings": string;
        /**
          * The Agent identifier
         */
        "identifier": string;
        /**
          * The language
         */
        "language"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface ChatComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChatComponentElement;
}
declare global {
    interface HTMLChatComponentElementEventMap {
        "send": any;
        "receiver": any;
    }
    interface HTMLChatComponentElement extends Components.ChatComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChatComponentElementEventMap>(type: K, listener: (this: HTMLChatComponentElement, ev: ChatComponentCustomEvent<HTMLChatComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChatComponentElementEventMap>(type: K, listener: (this: HTMLChatComponentElement, ev: ChatComponentCustomEvent<HTMLChatComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChatComponentElement: {
        prototype: HTMLChatComponentElement;
        new (): HTMLChatComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "chat-component": HTMLChatComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ChatComponent {
        /**
          * The Chat identifier
         */
        "chatUid"?: string;
        /**
          * The greetings
         */
        "greetings"?: string;
        /**
          * The Agent identifier
         */
        "identifier"?: string;
        /**
          * The language
         */
        "language"?: string;
        "onReceiver"?: (event: ChatComponentCustomEvent<any>) => void;
        "onSend"?: (event: ChatComponentCustomEvent<any>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "chat-component": ChatComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chat-component": LocalJSX.ChatComponent & JSXBase.HTMLAttributes<HTMLChatComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
